# Generated by Django 4.2.10 on 2024-02-19 19:37

import django.core.validators
from django.db import migrations, models
import exam_prep_my_music_app.profiles.models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    exam_prep_my_music_app.profiles.models.validate_username,
                ],
            ),
        ),
    ]
