# Generated by Django 4.1.1 on 2022-09-19 16:42

from django.db import migrations, models


# 0001_initial.py

class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
