# Generated by Django 4.2.10 on 2024-02-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_category_todo_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="web.category",
            ),
            preserve_default=False,
        ),
    ]
