# Generated by Django 4.2.10 on 2024-02-19 16:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("artist_name", models.CharField(max_length=30)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Pop Music", "Pop Music"),
                            ("Jazz Music", "Jazz Music"),
                            ("Rock Music", "Rock Music"),
                            ("Country Music", "Country Music"),
                            ("R&B Music", "R&B Music"),
                            ("Dance Music", "Dance Music"),
                            ("Hip Hop Music", "Hip Hop Music"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField()),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
    ]
