# Generated by Django 4.2.10 on 2024-02-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="artist_name",
            field=models.CharField(max_length=30, verbose_name="Artist"),
        ),
        migrations.AlterField(
            model_name="album",
            name="image_url",
            field=models.URLField(verbose_name="Image URL"),
        ),
        migrations.AlterField(
            model_name="album",
            name="name",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Album Name"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
    ]
