# Generated by Django 4.2.10 on 2024-02-12 17:51

import class_based_views_advanced.web.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="slug",
            field=models.SlugField(
                default=class_based_views_advanced.web.models.generate_slug,
                editable=False,
            ),
        ),
    ]
