# Generated by Django 4.2.10 on 2024-02-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_todo_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="tenant",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="slug",
            field=models.SlugField(editable=False),
        ),
    ]
