# Generated by Django 4.2.9 on 2024-01-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=35)),
                ("last_name", models.CharField(max_length=35)),
                (
                    "role",
                    models.IntegerField(
                        choices=[(1, "Software Developer"), (2, "QA engineer")]
                    ),
                ),
            ],
        ),
    ]
