# Generated by Django 4.2.9 on 2024-01-22 19:34

from django.db import migrations, models
import django.db.models.deletion
import form_basics.web.models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                max_length=35, validators=[form_basics.web.models.non_empty_spaces]
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="web.department",
            ),
        ),
    ]
