# Generated by Django 4.0.1 on 2022-01-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_egn_alter_employee_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id2', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, default='NO NAME', max_length=40, null=True),
        ),
    ]
