# Generated by Django 4.0.1 on 2022-01-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('SoftUni', 'SoftUni'), ('Google', 'Google'), ('Facebook', 'Facebook'), ('AUDI', 'AUDI')], max_length=8),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dead_line', models.DateField(blank=True, null=True)),
                ('employees', models.ManyToManyField(to='employees.Employee')),
            ],
        ),
    ]
