# Generated by Django 4.0.1 on 2022-02-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
