# Generated by Django 4.1.1 on 2022-10-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0012_employee_is_full_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jr', 'Junior'), ('reg', 'Regular'), ('sr', 'Senior')], max_length=3),
        ),
    ]
