# Generated by Django 4.1.1 on 2022-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0030_fill_slug_for_existing_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='none', unique=True),
            preserve_default=False,
        ),
    ]
