# Generated by Django 4.2.9 on 2024-01-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_person_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="web/profile_images"
            ),
        ),
    ]
